# Generated by Django 6.0.7 on 2026-08-04 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='age_category',
            field=models.CharField(choices=[('6-11', 'Младшие классы (6-11 лет)'), ('12-15', 'Средние классы (12-15 лет)'), ('16-18', 'Старшие классы и студенты (16-18 лет)')], default='12-15', max_length=10, verbose_name='Возраст участников'),
        ),
        migrations.AddField(
            model_name='course',
            name='course_format',
            field=models.CharField(choices=[('online', 'Онлайн-курс'), ('hybrid', 'Интенсив / Смешанный')], default='online', max_length=10, verbose_name='Формат обучения'),
        ),
        migrations.AddField(
            model_name='course',
            name='theme',
            field=models.CharField(choices=[('media', 'Медиа и коммуникации'), ('leadership', 'Лидерство и команда'), ('science', 'Наука и технологии'), ('volunteering', 'Волонтерство и добрые дела')], default='media', max_length=30, verbose_name='Тема курса'),
        ),
    ]
