# Generated by Django 6.0.7 on 2026-08-11 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_age_category_course_course_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'А'), ('B', 'Б'), ('C', 'В'), ('D', 'Г')], max_length=1, null=True, verbose_name='Буква правильного ответа (A, B, C, D)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант А'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант Б'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант В'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вариант Г'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='test_question',
            field=models.TextField(blank=True, null=True, verbose_name='Вопрос теста'),
        ),
    ]
